### PR TITLE
Add "Show all people" setting

### PR DESCRIPTION
**Pull request by CyberShadow**
Allow filtering out people who are in spaces from the Home space, in exactly the same way that rooms can already be filtered.

Because I (or a bridge/bot) already arranged all the DM rooms into spaces appropriately, so having them repeated in the Home space is redundant, and it's much more useful to be able to see DM rooms which haven't been sorted anywhere yet. Just like for the non-DM rooms.

This is a feature I've found missing in Element, perhaps you'd be interested in carrying this patch?

Screenshots:

image

image 

-----------------------------------------------------------------------------

~~I'm targeting this PR to `master` because `sc` is for reasons unknown to me very different, and `schildichat-desktop`'s submodule references a commit in `matrix-react-sdk` which is much closer to `master` than `sc`. I don't even know how to test `sc`, because `schildichat-desktop:sc` does not build with `matrix-react-sdk:sc`.~~

- [X] I agree to release my changes under this project's license

### CODE REVIEW

**Comment by su-ex** [comment]
Maybe I'd be open to carrying this, however, schildi threats treats rooms and dms normally as the same without separate nomenclature, so having to options there might be confusing.
No development ever happens in the `master` branch, this must go to `sc`.

**Comment by CyberShadow** [comment]
> however, schildi treats rooms and dms normally as the same without separate nomenclature, so having two options there might be confusing.

I'm open to merging this into one option. That would also simplify the patch a little. The big downside of doing so is that it would then become impossible to configure Schildichat to work like Element, i.e. show all people in Home but only orphan rooms.

> No development ever happens in the `master` branch, this must go to `sc`.

Thanks, rebased.

**Comment by su-ex** [comment]
> show all people in Home but only orphan rooms

Why would anyone want that? I can't grasp that at all.

**Comment by CyberShadow** [comment]
Well, I'm going to play devil's advocate here because I personally don't need that feature, but let's look at it from the perspective of a typical Matrix user.

- The user will typically end up in non-DM rooms in one of these ways:
  - They join the room directly
  - They join the room via its parent space
  - They create the room.
- But, the user can end up in DM rooms in one of these ways:
  - They create the room (by DM-ing someone)
  - Someone invites them to the room (by DM-ing them).

This is, I think, also the most important distinction between DM and non-DM rooms: how they are created.

This distinction is also going to affect where the room is going to end up in the user's space hierarchy. Spaces seem to be becoming the primary way for people to discover [non-space non-DM] rooms, whereas DM rooms are never going to be in a space unless one of the users puts it there (probably for personal categorization).

One exception to the above is bridged rooms. Bridges can put DM rooms inside the spaces they manage (e.g. mautrix-discord does this).

So, the questions "Do I want to see orphan non-DM rooms in Home?" and "Do I want to see orphan DM rooms in Home?" seem orthogonal. The first one is entirely to the user's preference. The second one is only relevant if the user uses bridges which put rooms in DMs, or they do that themselves, and then the answer also depends on the user's preferences.

So, to answer the stated question... if an Element user who uses bridges which put DM rooms in spaces switches to SchildiChat, hypothetically they may find that they can no longer access their DM rooms from Home as an unpleasant surprise.

**Comment by su-ex** [comment]
Sorry for not getting back to it any sooner.
Since you have already implemented this, let's just go with it.
Please fix the confilcts so I can merge it.

**Comment by CyberShadow** [comment]
Hi!

Well, after implementing all this & using it for a while, I can say that it does work fine. But also I realized that this functionality can be implemented simpler and cleaner with a bot (that runs under your account).

To be honest I did not expect the diff to be so big, so I would feel bad about asking you to carry this somewhat invasive patch and take away maintenance time that could be used to improve SchildiChat in other ways. I would be OK to close this and reimplement this in my personal bot (by sorting stray DM rooms into some kind of "TODO" space).

As such feel free to close this if you are on the fence about carrying this patch. Thanks!

**Comment by CyberShadow** [comment]
Closing this for the reasons stated above.

**Pull request closed without merging**
